### ISSUE TITLE
Autorun index can be set to infinity

### ISSUE THREAD

**Issue by BeaconBrigade** [mendelsshop/loading_bar#3]
When using `LoadingBar::auto_run` you can set the length and start parameters to be the same. When the index is calculated in line 102 of src/lib.rs with `let index = time_in_seconds as f32 / (len - start) as f32;`, index while be set to `inf` because of division by 0. This  will crash the program in this line:

line 112 src/lib.rs: `self_clone.advance_by_print(start);`

```
thread 'main' panicked at ' You can't advance more than the length of the bar', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/loading_bar-1.0.0/src/lib.rs:139:13

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I believe this is happening because the program tries to advance by the length of the bar which is  larger than the length of the bar. And if the program kept going, the program it would then crash by trying to `std::thread::sleep` for `inf` seconds.

I guess it might be better to return a `Result` so you can tell the caller that they passed invalid parameters, and they can handle the errors themselves.

**Comment by mendelsshop** [comment]
Right now just for fun I'm going to make it panic but not in the adv_index method rather in the autorun function in line 97 in src/lib.rs instead of `if start > len ...`  I'll do  `if start >= len ...`  so that the panic is more descriptive ie: it will panic at line 99 instead of line 139. Eventually I'd like to use Result where there are panic, I'm just to lazy to do it right now.

**Comment by mendelsshop** [comment]
fixed see https://github.com/mendelsshop/loading_bar/commit/c8c21d14fc45a67b2e996b968a356fbe78afb40f, also do you mind if I credit you in README.md?

**Comment by BeaconBrigade** [comment]
Ah.. I understand. No I don't mind being credited in the README. If there's anything I can do, I'd be happy to help.
