### ISSUE TITLE
Auto Run possibly not working

### ISSUE THREAD

**Issue by BeaconBrigade** [mendelsshop/loading_bar#4]
While playing around with your library, I couldn't get `auto_run` to work although everything else did. I'm not sure whether this is just a problem with my computer or not. After looking more at your code for `auto_run`, I have a question. When you initialize a loading bar using:

```rust,ignore
let mut self_clone = LoadingBar {
    len,
    index: start,
    done: false,
    color,
    space_left: len - start,
    half: false,
    start_pos,
};
```

From my understanding, `index` keeps track of how far along the bar is, which is why you set it to `start`. But, on the next line you call 

```rust,ignore
self_clone.advance_by_print(start);
```

which increments the `index` by `start` after it has already been set to `start`. I'm posting this issue as a question. Is this supposed to happen? Sorry to bother you.

**Comment by mendelsshop** [comment]
Oops, gonna change that soon, and you're not bothering me, I feel very cool now, b/c this is my first project where I got a lot of user input and collaboration.

**Comment by mendelsshop** [comment]
Actually that is supposed to happen b/c `start` refers to where the index should start from, i.e., if the user doesn't want to start from the beginning of the `LoadingBar` but rather in the middle etc.

**Comment by mendelsshop** [comment]
Oops, you're right, I totally skimmed your diagnoses, I removed the call to `advance_by_print` and replaced it with a call to `print`. Gonna this soon, just working on another feature too.

**Comment by mendelsshop** [comment]
Fixed see https://github.com/mendelsshop/loading_bar/commit/452c1b36a706bdadebe3f202d1412fd32b6aca88#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R166

**Comment by BeaconBrigade** [comment]
I've just been getting into Rust and happened to see your project on [crates.io](https://crates.io/crates/loading_bar) which I thought was pretty interesting. I was playing around with your library when I noticed the spelling mistake and thought I might be able to make a *contribution*. I'm also having a lot of fun starting with Github and getting to help out on an actually interesting project. :)
